#!/usr/bin/env bash
set -ex

npm install

rm -rf ./dist

# ./node_modules/.bin/tsc
./node_modules/.bin/tsup

pushd downstream-package
  npm install

  # Test types
  ../node_modules/.bin/tsc

  node ./dist/cjs-test.js
  node ./dist/esm-test.mjs
popd

./node_modules/.bin/attw --pack
