#!/usr/bin/env bash
set -ex

npm install

rm -rf ./dist

# ./node_modules/.bin/tsc
./node_modules/.bin/tsup

pushd downstream-package
  npm install
  ./node_modules/.bin/tsx cjs-test.ts
  ./node_modules/.bin/tsx esm-test.mts

  # Test types
  ../node_modules/.bin/tsc --noEmit
popd

./node_modules/.bin/attw --pack
